[project]
name = "hands-on-modern-rl-pq"
version = "0.1.0"
description = "Environment for hands-on reinforcement learning course"
requires-python = ">=3.10"
dependencies = [
    "accelerate==1.10.1",
    "ale-py>=0.10.0",
    "datasets==4.4.1",
    "gymnasium[accept-rom-license,atari,classic-control,mujoco]>=0.29.0",
    "json5>=0.9.0",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "pyboy>=2.0.0",
    "stable-baselines3>=2.0.0",
    "swanlab[dashboard]>=0.3.0",
    "tensorboard>=2.14.0",
    "torch>=2.0.0",
    "transformers==4.57.3",
    "trl==0.24.0",
]
